Repository anitvam/pps-bunny, pull requests merged in 2021-10, with the labels that each got.

#72 Population legend fixes and ScalaFXConstants refactoring.
  src/main/resources/fxml/stylesheets/style.css
  src/main/scala/view/scalaFX/FXControllers/BaseAppController.scala
  src/main/scala/view/scalaFX/FXControllers/ChartChoiceController.scala
  src/main/scala/view/scalaFX/FXControllers/FactorsPanelController.scala
  src/main/scala/view/scalaFX/FXControllers/MutationsPanelController.scala
  src/main/scala/view/scalaFX/ScalaFXConstants.scala
  src/main/scala/view/scalaFX/ScalaFXView.scala
  src/main/scala/view/scalaFX/components/BunnyView.scala
  src/main/scala/view/scalaFX/components/WolfView.scala
  src/main/scala/view/scalaFX/components/charts/PopulationChart.scala
  src/main/scala/view/scalaFX/components/charts/pedigree/BunnyPedigreeView.scala
  src/main/scala/view/scalaFX/components/charts/pedigree/PedigreeChart.scala
  src/main/scala/view/scalaFX/utilities/Direction.scala
  src/main/scala/view/scalaFX/utilities/FxmlUtils.scala
  src/main/scala/view/scalaFX/utilities/PimpScalaFXChartLibrary.scala
  src/main/scala/view/scalaFX/utilities/ViewImages.scala
Labels: BUG

#74 Fix reset of mutations panel.
  src/main/scala/model/genome/Kinds.scala
  src/main/scala/model/mutation/Mutation.scala
  src/main/scala/view/scalaFX/FXControllers/BaseAppController.scala
  src/main/scala/view/scalaFX/FXControllers/MutationsPanelController.scala
Labels: BUG

#75 Fix Pedigree overlapping in width.
  src/main/scala/view/scalaFX/ScalaFXConstants.scala
  src/main/scala/view/scalaFX/components/charts/pedigree/BunnyPedigreeView.scala
  src/main/scala/view/scalaFX/components/charts/pedigree/PedigreeChart.scala
Labels: BUG, GUI

#76 Minor refactoring of Bunny model.
  src/main/scala/controller/Controller.scala
  src/main/scala/engine/SimulationHistory.scala
  src/main/scala/model/Bunny.scala
  src/main/scala/model/genome/Genotype.scala
  src/main/scala/model/genome/Kinds.scala
  src/main/scala/model/world/Environment.scala
  src/main/scala/model/world/Mutation.scala
  src/main/scala/model/world/Reproduction.scala
  src/main/scala/util/PimpScala.scala
  src/main/scala/view/scalaFX/FXControllers/BaseAppController.scala
  src/main/scala/view/scalaFX/FXControllers/MutationsPanelController.scala
  src/main/scala/view/scalaFX/FXControllers/ProportionsChartController.scala
  src/main/scala/view/scalaFX/components/BunnyView.scala
  src/test/scala/model/TestBunny.scala
  src/test/scala/model/TestGenes.scala
  src/test/scala/model/TestMutations.scala
Labels: Model

#77 Introduced speedUp, integrated restart and engine refactoring
  src/main/resources/fxml/baseApp.fxml
  src/main/resources/fxml/stylesheets/style.css
  src/main/resources/img/restart.png
  src/main/resources/img/speeddown.png
  src/main/resources/img/speedup.png
  src/main/scala/controller/Controller.scala
  src/main/scala/engine/Simulation.scala
  src/main/scala/engine/SimulationConstants.scala
  src/main/scala/engine/SimulationEngine.scala
  src/main/scala/engine/SimulationHistory.scala
  src/main/scala/model/world/Generation.scala
  src/main/scala/view/View.scala
  src/main/scala/view/scalaFX/FXControllers/BaseAppController.scala
  src/main/scala/view/scalaFX/FXControllers/FactorsPanelController.scala
  src/main/scala/view/scalaFX/FXControllers/ProportionsChartController.scala
  src/main/scala/view/scalaFX/ScalaFXView.scala
Labels: Model, GUI

#80 Updated population and proportions charts
  src/main/resources/fxml/proportionsChartPane.fxml
  src/main/scala/controller/Controller.scala
  src/main/scala/engine/SimulationHistory.scala
  src/main/scala/model/Bunny.scala
  src/main/scala/model/world/Generation.scala
  src/main/scala/model/world/Reproduction.scala
  src/main/scala/view/scalaFX/FXControllers/BaseAppController.scala
  src/main/scala/view/scalaFX/FXControllers/ChartChoiceController.scala
  src/main/scala/view/scalaFX/FXControllers/ProportionsChartController.scala
  src/main/scala/view/scalaFX/ScalaFXConstants.scala
  src/main/scala/view/scalaFX/components/charts/PopulationChart.scala
  src/main/scala/view/scalaFX/utilities/PimpScalaFXChartLibrary.scala
  src/test/scala/model/TestReproduction.scala
Labels: GUI

#81 Fix problem with Linux and Javafx
  src/main/scala/controller/ScalaFXLauncher.scala
Labels: BUG

#64 Add genetics introduction.
  doc/report.md
Labels: Documentation

#91 add panels to show overpopulation end and show over generation end
  src/main/resources/img/extinction.png
  src/main/resources/img/generations_overload.png
  src/main/scala/view/scalaFX/ScalaFXView.scala
Labels: GUI

#78 Feature/ar gui clock
  src/main/resources/fxml/baseApp.fxml
  src/main/resources/fxml/chartChoiceSelection.fxml
  src/main/resources/fxml/mutationsPanel.fxml
  src/main/resources/fxml/stylesheets/clock.css
  src/main/scala/controller/Controller.scala
  src/main/scala/engine/Simulation.scala
  src/main/scala/engine/SimulationConstants.scala
  src/main/scala/engine/SimulationEngine.scala
  src/main/scala/model/world/Generation.scala
  src/main/scala/view/scalaFX/FXControllers/BaseAppController.scala
  src/main/scala/view/scalaFX/FXControllers/ChartChoiceController.scala
  src/main/scala/view/scalaFX/ScalaFXView.scala
  src/main/scala/view/scalaFX/components/ClockView.scala
Labels: GUI

#93 Add gender in the Bunny.
  src/main/resources/prolog/pedigree_dim.pl
  src/main/scala/engine/SimulationHistory.scala
  src/main/scala/model/Exceptions.scala
  src/main/scala/model/bunny/Bunny.scala
  src/main/scala/model/bunny/Tree.scala
  src/main/scala/model/genome/Kinds.scala
  src/main/scala/model/world/Generation.scala
  src/main/scala/model/world/Reproduction.scala
  src/main/scala/model/world/disturbingFactors/FoodFactor.scala
  src/main/scala/model/world/disturbingFactors/UnfriendlyClimateFactor.scala
  src/main/scala/model/world/disturbingFactors/WolvesFactor.scala
  src/main/scala/util/PimpScala.scala
  src/main/scala/util/Scala2P.scala
  src/main/scala/view/scalaFX/FXControllers/ProportionsChartController.scala
  src/main/scala/view/scalaFX/components/BunnyView.scala
  src/main/scala/view/scalaFX/components/charts/pedigree/BunnyPedigreeView.scala
  src/main/scala/view/scalaFX/components/charts/pedigree/PedigreeChart.scala
  src/main/scala/view/scalaFX/utilities/BunnyImages.scala
  src/test/scala/model/TestBunny.scala
  src/test/scala/model/TestFactors.scala
  src/test/scala/model/TestGenes.scala
  src/test/scala/model/TestMutations.scala
  src/test/scala/model/TestReproduction.scala
  src/test/scala/model/TestSimulation.scala
  src/test/scala/model/TestTree.scala
  src/test/scala/view/TestTreeVisualization.scala
Labels: Model, GUI

#97 fix bug pedigree legend when restart
  src/main/scala/it/unibo/pps/bunny/view/scalaFX/FXControllers/ChartChoiceController.scala
Labels: BUG

#96 Added more test for SimulationHistory
  build.sbt
  src/main/scala/it/unibo/pps/bunny/controller/Controller.scala
  src/main/scala/it/unibo/pps/bunny/engine/SimulationEngine.scala
  src/main/scala/it/unibo/pps/bunny/engine/SimulationHistory.scala
  src/test/scala/it/unibo/pps/bunny/model/TestSimulation.scala
Labels: CI & Testing

#99 Refactoring of Mutation
  src/main/scala/it/unibo/pps/bunny/controller/Controller.scala
  src/main/scala/it/unibo/pps/bunny/model/genome/Kinds.scala
  src/main/scala/it/unibo/pps/bunny/model/mutation/Mutation.scala
  src/main/scala/it/unibo/pps/bunny/model/world/Environment.scala
  src/main/scala/it/unibo/pps/bunny/view/scalaFX/FXControllers/MutationsPanelController.scala
  src/test/scala/it/unibo/pps/bunny/model/TestMutations.scala
Labels: Model

#103 Added test for Environment
  src/main/scala/it/unibo/pps/bunny/model/world/Environment.scala
  src/main/scala/it/unibo/pps/bunny/model/world/disturbingFactors/PimpFactors.scala
  src/test/scala/it/unibo/pps/bunny/model/TestEnvironment.scala
Labels: CI & Testing

#101 Fix/ar speed up button and minor refactor
  src/main/resources/fxml/baseApp.fxml
  src/main/scala/it/unibo/pps/bunny/engine/SimulationConstants.scala
  src/main/scala/it/unibo/pps/bunny/model/world/Generation.scala
  src/main/scala/it/unibo/pps/bunny/view/scalaFX/FXControllers/BaseAppController.scala
  src/main/scala/it/unibo/pps/bunny/view/scalaFX/components/AnimalViewUtils.scala
  src/main/scala/it/unibo/pps/bunny/view/scalaFX/components/BunnyView.scala
  src/main/scala/it/unibo/pps/bunny/view/scalaFX/components/ClockView.scala
  src/main/scala/it/unibo/pps/bunny/view/scalaFX/components/WolfView.scala
  src/main/scala/it/unibo/pps/bunny/view/scalaFX/utilities/EnvironmentImages.scala
  src/main/scala/it/unibo/pps/bunny/view/scalaFX/utilities/PimpScalaFXChartLibrary.scala
  src/test/scala/it/unibo/pps/bunny/model/bunny/TestTree.scala
  src/test/scala/it/unibo/pps/bunny/model/factors/TestFactorsComposition.scala
  src/test/scala/it/unibo/pps/bunny/model/genome/TestKinds.scala
Labels: GUI

#119 Added detailed design, future developments proposals and Product Backlog.
  doc/images/bunny_model.png
  doc/report.md
  process/Product_Backlog.pdf
Labels: Documentation

#122 Documentation for future development proposals (integrated with Rocco)
  doc/report.md
Labels: Documentation

#124 General report refactor
  doc/report.md
Labels: Documentation
