Repository anitvam/pps-bunny, pull requests merged in 2021-09, with the labels that each got.

#9 Basic model for the bunny
  src/main/scala/TestClass.scala
  src/main/scala/model/Bunny.scala
  src/main/scala/model/Exceptions.scala
  src/main/scala/model/genome/Gene.scala
  src/main/scala/model/genome/Genotype.scala
  src/main/scala/model/genome/Kinds.scala
  src/main/scala/model/world/Reproduction.scala
  src/test/scala/TestClass.scala
  src/test/scala/model/TestBunny.scala
  src/test/scala/model/TestGenes.scala
  src/test/scala/model/TestKinds.scala
Labels: Model

#10 Add first implementation of the GUI with the management of bunnies population
  build.sbt
  src/main/resources/fxml/baseApp.fxml
  src/main/scala/controller/ScalaFXLauncher.scala
  src/main/scala/view/View.scala
  src/main/scala/view/scalaFX/FXControllers/BaseAppController.scala
  src/main/scala/view/scalaFX/ScalaFXView.scala
  src/main/scala/view/scalaFX/components/BunnyView.scala
  src/main/scala/view/scalaFX/utilities/Direction.scala
  src/main/scala/view/utilities/BunnyImage.scala
Labels: GUI

#14 Model definition of application engine
  build.sbt
  src/main/resources/fxml/baseApp.fxml
  src/main/scala/controller/Controller.scala
  src/main/scala/controller/ScalaFXLauncher.scala
  src/main/scala/engine/GenerationTimer.scala
  src/main/scala/engine/Simulation.scala
  src/main/scala/engine/SimulationConstants.scala
  src/main/scala/engine/SimulationEngine.scala
  src/main/scala/engine/SimulationHistory.scala
  src/main/scala/model/world/Generation.scala
  src/main/scala/model/world/Reproduction.scala
  src/main/scala/view/View.scala
  src/main/scala/view/scalaFX/FXControllers/BaseAppController.scala
  src/main/scala/view/scalaFX/ScalaFXView.scala
  src/test/scala/model/TestBunny.scala
Labels: Model

#13 Generation of genealogical tree of Bunny.
  src/main/scala/engine/SimulationConstants.scala
  src/main/scala/model/Bunny.scala
  src/main/scala/model/BunnyConstants.scala
  src/main/scala/model/genome/Gene.scala
  src/main/scala/model/world/Reproduction.scala
  src/test/scala/model/TestBunny.scala
  src/test/scala/model/TestTree.scala
Labels: Model

#28 Update java VM dependencies inside CI
  .github/workflows/ci.yml
Labels: BUG, CI & Testing

#29 Feature/ar model mutations
  src/main/scala/engine/SimulationHistory.scala
  src/main/scala/model/genome/Gene.scala
  src/main/scala/model/genome/Kinds.scala
  src/main/scala/model/mutation/Mutation.scala
  src/main/scala/model/world/Reproduction.scala
  src/test/scala/model/TestGenes.scala
  src/test/scala/model/TestKinds.scala
  src/test/scala/model/TestMutations.scala
Labels: Model

#34 Add Population Chart
  src/main/resources/fxml/baseApp.fxml
  src/main/resources/fxml/stylesheets/style.css
  src/main/scala/engine/Simulation.scala
  src/main/scala/engine/SimulationConstants.scala
  src/main/scala/engine/SimulationEngine.scala
  src/main/scala/engine/SimulationHistory.scala
  src/main/scala/model/genome/Kinds.scala
  src/main/scala/model/world/Generation.scala
  src/main/scala/view/View.scala
  src/main/scala/view/scalaFX/FXControllers/BaseAppController.scala
  src/main/scala/view/scalaFX/ScalaFXView.scala
  src/main/scala/view/scalaFX/components/BunnyView.scala
  src/main/scala/view/scalaFX/components/charts/PopulationChart.scala
  src/main/scala/view/scalaFX/utilities/PimpScala.scala
  src/main/scala/view/scalaFX/utilities/PimpScalaFXChartLibrary.scala
Labels: GUI

#32 Documentation CI and Development Process initialization
  doc/images/git_flow.svg
  doc/report.md
Labels: Documentation

#38 Added Proportions Chart
  src/main/resources/fxml/chartChoiceSelection.fxml
  src/main/resources/fxml/proportionsChartPane.fxml
  src/main/resources/fxml/stylesheets/style.css
  src/main/scala/controller/Controller.scala
  src/main/scala/view/scalaFX/FXControllers/BaseAppController.scala
  src/main/scala/view/scalaFX/FXControllers/ProportionsChartController.scala
  src/main/scala/view/scalaFX/ScalaFXView.scala
  src/main/scala/view/scalaFX/components/charts/PopulationChart.scala
  src/main/scala/view/scalaFX/utilities/PimpScalaFXChartLibrary.scala
Labels: GUI

#35 Documentation for Development Process, Business Requirements and User Requirements
  doc/report.md
Labels: Documentation

#62 fixed the size of images of bunnies with long ears
  src/main/resources/img/bunnies/brown/long_ears/long_teeth/normal_fur/normal.png
  src/main/resources/img/bunnies/brown/long_ears/long_teeth/thick_fur/normal.png
  src/main/resources/img/bunnies/brown/long_ears/normal_teeth/normal_fur/normal.png
  src/main/resources/img/bunnies/brown/long_ears/normal_teeth/thick_fur/normal.png
  src/main/resources/img/bunnies/white/long_ears/long_teeth/normal_fur/normal.png
  src/main/resources/img/bunnies/white/long_ears/long_teeth/thick_fur/normal.png
  src/main/resources/img/bunnies/white/long_ears/normal_teeth/normal_fur/normal.png
  src/main/resources/img/bunnies/white/long_ears/normal_teeth/thick_fur/normal.png
Labels: BUG

#61 Updated Pedigree View.
  src/main/resources/fxml/chartChoiceSelection.fxml
  src/main/resources/fxml/mutationsPanel.fxml
  src/main/resources/fxml/proportionsChartPane.fxml
  src/main/scala/model/genome/Kinds.scala
  src/main/scala/util/PimpScala.scala
  src/main/scala/view/scalaFX/FXControllers/ChartChoiceController.scala
  src/main/scala/view/scalaFX/FXControllers/ProportionsChartController.scala
  src/main/scala/view/scalaFX/ScalaFXView.scala
  src/main/scala/view/scalaFX/components/charts/pedigree/BunnyPedigreeView.scala
  src/main/scala/view/scalaFX/components/charts/pedigree/PedigreeChart.scala
Labels: GUI

#65 Added in Generation the living population
  src/main/scala/engine/SimulationHistory.scala
  src/main/scala/model/world/Generation.scala
  src/test/scala/model/TestSimulation.scala
Labels: BUG

#63 Reproduction refactoring and minor fixes.
  src/main/scala/engine/SimulationHistory.scala
  src/main/scala/model/Bunny.scala
  src/main/scala/model/world/Reproduction.scala
  src/main/scala/util/PimpScala.scala
  src/main/scala/view/scalaFX/ScalaFXView.scala
  src/main/scala/view/scalaFX/components/charts/pedigree/BunnyPedigreeView.scala
  src/main/scala/view/scalaFX/components/charts/pedigree/PedigreeChart.scala
  src/test/scala/model/TestBunny.scala
  src/test/scala/model/TestReproduction.scala
Labels: Model

#68 Solved click on bunny problem and refactor of BunnyView
  src/main/resources/fxml/baseApp.fxml
  src/main/scala/view/scalaFX/FXControllers/BaseAppController.scala
  src/main/scala/view/scalaFX/components/BunnyView.scala
Labels: BUG

#66 Added text on pedigree chart choice with no clicked bunny
  .scalafmt 2.conf
  src/main/resources/fxml/baseApp.fxml
  src/main/scala/view/scalaFX/FXControllers/BaseAppController.scala
Labels: BUG, GUI

#67 Disturbing Factors Model
  src/main/scala/engine/Simulation.scala
  src/main/scala/engine/SimulationConstants.scala
  src/main/scala/engine/SimulationEngine.scala
  src/main/scala/engine/SimulationHistory.scala
  src/main/scala/model/world/DisturbingFactor.scala
  src/main/scala/model/world/Environment.scala
  src/main/scala/view/scalaFX/FXControllers/BaseAppController.scala
  src/main/scala/view/scalaFX/FXControllers/ProportionsChartController.scala
  src/test/scala/model/TestFactors.scala
Labels: Model

#70 Better images for the info in the pedigree chart.
  .scalafmt 2.conf
  src/main/resources/img/death.png
  src/main/resources/img/mutation.png
  src/main/scala/util/PimpScala.scala
  src/main/scala/view/scalaFX/FXControllers/BaseAppController.scala
  src/main/scala/view/scalaFX/ScalaFXView.scala
  src/main/scala/view/scalaFX/components/BunnyView.scala
  src/main/scala/view/scalaFX/components/charts/PopulationChart.scala
  src/main/scala/view/scalaFX/components/charts/pedigree/BunnyPedigreeView.scala
  src/main/scala/view/scalaFX/components/charts/pedigree/PedigreeChart.scala
  src/main/scala/view/scalaFX/utilities/Direction.scala
  src/main/scala/view/scalaFX/utilities/FxmlUtils.scala
  src/main/scala/view/scalaFX/utilities/PimpScalaFXChartLibrary.scala
  src/main/scala/view/scalaFX/utilities/ViewImages.scala
Labels: BUG, GUI

#69 Gameplay restart after simulation ends.
  src/main/resources/fxml/baseApp.fxml
  src/main/resources/fxml/chartChoiceSelection.fxml
  src/main/resources/fxml/mutationsPanel.fxml
  src/main/scala/controller/Controller.scala
  src/main/scala/engine/Simulation.scala
  src/main/scala/engine/SimulationHistory.scala
  src/main/scala/view/scalaFX/FXControllers/BaseAppController.scala
  src/main/scala/view/scalaFX/FXControllers/ChartChoiceController.scala
  src/main/scala/view/scalaFX/FXControllers/MutationsPanelController.scala
  src/main/scala/view/scalaFX/FXControllers/ProportionsChartController.scala
  src/main/scala/view/scalaFX/ScalaFXView.scala
  src/main/scala/view/scalaFX/components/charts/PopulationChart.scala
  src/main/scala/view/scalaFX/components/charts/pedigree/PedigreeChart.scala
  src/main/scala/view/scalaFX/utilities/Chart.scala
Labels: Model, GUI
